# Generated by Django 2.0.13 on 2019-03-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_facility_facilitylistitem_country_code_vietnam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylist',
            name='contributor',
            field=models.ForeignKey(help_text='The contributor that uploaded this list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Contributor'),
        ),
    ]
