# Generated by Django 2.0.10 on 2019-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_make_facility_list_contributor_fk_nullable_20190319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylistitem',
            name='geocoded_address',
            field=models.CharField(blank=True, help_text='The geocoded address of the facility.', max_length=1000, null=True),
        ),
    ]
