# Generated by Django 2.0.13 on 2019-05-22 20:02

from django.db import migrations


def create_claim_a_facility_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(name='claim_a_facility', active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0003_update_strings_for_i18n'),
        ('api', '0006_change_macedonia_country_name'),
    ]

    operations = [
        migrations.RunPython(create_claim_a_facility_switch)
    ]
