# Generated by Django 2.0.10 on 2019-06-05 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_facilityclaim_historicalfacilityclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContributor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the contributor.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the contributor.')),
                ('website', models.URLField(blank=True, help_text='A URL linking to a web site for the contributor.')),
                ('contrib_type', models.CharField(choices=[('Auditor', 'Auditor'), ('Brand/Retailer', 'Brand/Retailer'), ('Civil Society Organization', 'Civil Society Organization'), ('Factory / Facility', 'Factory / Facility'), ('Manufacturing Group / Supplier / Vendor', 'Manufacturing Group / Supplier / Vendor'), ('Multi Stakeholder Initiative', 'Multi Stakeholder Initiative'), ('Researcher / Academic', 'Researcher / Academic'), ('Service Provider', 'Service Provider'), ('Union', 'Union'), ('Other', 'Other')], help_text='The category to which this contributor belongs.', max_length=200)),
                ('other_contrib_type', models.CharField(blank=True, help_text='Free text field if selected contributor type is other', max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has this contributor has been verified by OAR staff.', verbose_name='verified')),
                ('verification_notes', models.TextField(blank=True, help_text='A description of the manual steps taken to verify the contributor.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin', models.ForeignKey(blank=True, db_constraint=False, help_text='The user account responsible for uploading and maintaining facility lists for the contributor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contributor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='contributor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has this contributor has been verified by OAR staff.', verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='A description of the manual steps taken to verify the contributor.'),
        ),
    ]
