# Generated by Django 2.0.13 on 2019-06-17 15:42

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_editable_fields_to_facility_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFacilityMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(help_text='Diagnostic details from the matching process.')),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='A numeric representation of how confident the app is that the list item matches the existing facility. Larger numbers are better.', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('AUTOMATIC', 'AUTOMATIC'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', help_text='The current status of the match. AUTOMATIC if the application made a match with high confidence. PENDING if confirmation from the contributor admin is required. CONFIRMED if the admin approves the match. REJECTED if the admin rejects the match. Only one row for a given and facility list item pair should have either AUTOMATIC or CONFIRMED status', max_length=9)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility', models.ForeignKey(blank=True, db_constraint=False, help_text='The existing facility that may match an uploaded list item.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Facility')),
                ('facility_list_item', models.ForeignKey(blank=True, db_constraint=False, help_text='The list item being matched to an existing facility.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.FacilityListItem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facility match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
