# Generated by Django 2.0.13 on 2019-06-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_historicalfacilitymatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAlias',
            fields=[
                ('oar_id', models.CharField(editable=False, help_text='The OAR ID of a no longer existent Facility which should be redirected to a different Facility.', max_length=32, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('MERGE', 'MERGE'), ('DELETE', 'DELETE')], help_text='The reason why this alias was created', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(help_text='The facility now associated with the oar_id', on_delete=django.db.models.deletion.PROTECT, to='api.Facility')),
            ],
        ),
    ]
