# Generated by Django 2.0.13 on 2019-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_faclilityalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylistitem',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('PARSED', 'PARSED'), ('GEOCODED', 'GEOCODED'), ('GEOCODED_NO_RESULTS', 'GEOCODED_NO_RESULTS'), ('MATCHED', 'MATCHED'), ('POTENTIAL_MATCH', 'POTENTIAL_MATCH'), ('CONFIRMED_MATCH', 'CONFIRMED_MATCH'), ('ERROR', 'ERROR'), ('ERROR_PARSING', 'ERROR_PARSING'), ('ERROR_GEOCODING', 'ERROR_GEOCODING'), ('ERROR_MATCHING', 'ERROR_MATCHING'), ('DELETED', 'DELETED')], default='UPLOADED', help_text='The current workflow progress of the line item.', max_length=200),
        ),
    ]
