# Generated by Django 2.0.13 on 2019-06-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_deleted_status_to_facility_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitymatch',
            name='facility',
            field=models.ForeignKey(help_text='The existing facility that may match an uploaded list item.', on_delete=django.db.models.deletion.PROTECT, to='api.Facility'),
        ),
        migrations.AlterField(
            model_name='facilitymatch',
            name='facility_list_item',
            field=models.ForeignKey(help_text='The list item being matched to an existing facility.', on_delete=django.db.models.deletion.PROTECT, to='api.FacilityListItem'),
        ),
    ]
