# Generated by Django 2.0.13 on 2019-06-21 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_change_facility_match_fks_to_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFacilityAlias',
            fields=[
                ('oar_id', models.CharField(db_index=True, editable=False, help_text='The OAR ID of a no longer existent Facility which should be redirected to a different Facility.', max_length=32)),
                ('reason', models.CharField(choices=[('MERGE', 'MERGE'), ('DELETE', 'DELETE')], help_text='The reason why this alias was created', max_length=6)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility', models.ForeignKey(blank=True, db_constraint=False, help_text='The facility now associated with the oar_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Facility')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical facility alias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
