# Generated by Django 2.0.13 on 2019-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_historicalfacilityalias')
    ]

    operations = [
        migrations.AddField(
            model_name='facilitymatch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='A facility match is_active if its associated list item not been removed; when a list item is removed, this field will be set to False.'),
        ),
        migrations.AddField(
            model_name='historicalfacilitymatch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='A facility match is_active if its associated list item not been removed; when a list item is removed, this field will be set to False.'),
        ),
    ]
