# Generated by Django 2.0.13 on 2019-06-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_is_active_field_to_facilitymatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityclaim',
            name='parent_company',
            field=models.ForeignKey(default=None, help_text='The parent company of this facility claim.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_company', to='api.Contributor'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='The parent company of this facility claim.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor'),
        ),
    ]
