# Generated by Django 2.0.13 on 2019-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_parent_company_to_facilityclaim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityalias',
            options={'verbose_name_plural': 'facility aliases'},
        ),
        migrations.AlterField(
            model_name='facilitymatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AUTOMATIC', 'AUTOMATIC'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED'), ('MERGED', 'MERGED')], default='PENDING', help_text='The current status of the match. AUTOMATIC if the application made a match with high confidence. PENDING if confirmation from the contributor admin is required. CONFIRMED if the admin approves the match. REJECTED if the admin rejects the match. Only one row for a given and facility list item pair should have either AUTOMATIC or CONFIRMED status', max_length=9),
        ),
        migrations.AlterField(
            model_name='historicalfacilitymatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AUTOMATIC', 'AUTOMATIC'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED'), ('MERGED', 'MERGED')], default='PENDING', help_text='The current status of the match. AUTOMATIC if the application made a match with high confidence. PENDING if confirmation from the contributor admin is required. CONFIRMED if the admin approves the match. REJECTED if the admin rejects the match. Only one row for a given and facility list item pair should have either AUTOMATIC or CONFIRMED status', max_length=9),
        ),
    ]
