# Generated by Django 2.0.13 on 2019-07-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_facilitymatch_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='The API token used to make the request', max_length=40)),
                ('method', models.CharField(help_text='The HTTP verb used to make the request', max_length=6)),
                ('path', models.CharField(help_text='The requested resource path', max_length=2083)),
                ('response_code', models.IntegerField(help_text='The HTTP status code returned to the requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The User account that made the request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
