# Generated by Django 2.0.13 on 2019-07-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_create_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityclaim',
            name='facility_website',
            field=models.URLField(blank=True, help_text='The editable facility website for this claim.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaim',
            name='facility_website',
            field=models.URLField(blank=True, help_text='The editable facility website for this claim.', null=True),
        ),
    ]
