# Generated by Django 2.0.13 on 2019-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_facilitylaim_website_to_urlfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityclaim',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityclaim',
            name='facility_name',
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_female_workers_percentage',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], help_text="Integer value indicating the facility's percentage of female workers.", null=True, verbose_name='percentage of female workers'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_name_english',
            field=models.CharField(blank=True, help_text='The editable official English facility name for the claim.', max_length=200, null=True, verbose_name='facility name in English'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_name_native_language',
            field=models.CharField(blank=True, help_text='The editable official native language facility name.', max_length=200, null=True, verbose_name='facility name in native language'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('Cut and Sew / RMG', 'Cut and Sew / RMG'), ('Dyehouse', 'Dyehouse'), ('Embellishments', 'Embellishments'), ('Fabric Mill', 'Fabric Mill'), ('Finishing', 'Finishing'), ('Ginning', 'Ginning'), ('Knitting', 'Knitting'), ('Laundry', 'Laundry'), ('Packing', 'Packing'), ('Scouring', 'Scouring'), ('Screenprinting', 'Screenprinting'), ('Stitching (Shoes)', 'Stitching (Shoes)'), ('Tannery', 'Tannery'), ('Warehouse', 'Warehouse'), ('Weaving', 'Weaving'), ('Other', 'Other')], help_text='The editable facility type for this claim.', max_length=17, null=True, verbose_name='facility type'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_website_publicly_visible',
            field=models.BooleanField(default=False, help_text='Is the website publicly visible?', verbose_name='facility website visible'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_workers_count',
            field=models.IntegerField(blank=True, help_text='The editable facility workers count for this claim.', null=True, verbose_name='facility workers count'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='job_title',
            field=models.CharField(default='', help_text="The contact person's job title", max_length=200, verbose_name="contact person's job title"),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='A LinkedIn profile for verifying the facility claim', verbose_name='verification LinkedIn profile'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='other_facility_type',
            field=models.CharField(blank=True, help_text='Editable alternate text when facility type is OTHER.', max_length=200, null=True, verbose_name='description of other facility type'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_female_workers_percentage',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], help_text="Integer value indicating the facility's percentage of female workers.", null=True, verbose_name='percentage of female workers'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_name_english',
            field=models.CharField(blank=True, help_text='The editable official English facility name for the claim.', max_length=200, null=True, verbose_name='facility name in English'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_name_native_language',
            field=models.CharField(blank=True, help_text='The editable official native language facility name.', max_length=200, null=True, verbose_name='facility name in native language'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('Cut and Sew / RMG', 'Cut and Sew / RMG'), ('Dyehouse', 'Dyehouse'), ('Embellishments', 'Embellishments'), ('Fabric Mill', 'Fabric Mill'), ('Finishing', 'Finishing'), ('Ginning', 'Ginning'), ('Knitting', 'Knitting'), ('Laundry', 'Laundry'), ('Packing', 'Packing'), ('Scouring', 'Scouring'), ('Screenprinting', 'Screenprinting'), ('Stitching (Shoes)', 'Stitching (Shoes)'), ('Tannery', 'Tannery'), ('Warehouse', 'Warehouse'), ('Weaving', 'Weaving'), ('Other', 'Other')], help_text='The editable facility type for this claim.', max_length=17, null=True, verbose_name='facility type'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_website_publicly_visible',
            field=models.BooleanField(default=False, help_text='Is the website publicly visible?', verbose_name='facility website visible'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_workers_count',
            field=models.IntegerField(blank=True, help_text='The editable facility workers count for this claim.', null=True, verbose_name='facility workers count'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='job_title',
            field=models.CharField(default='', help_text="The contact person's job title", max_length=200, verbose_name="contact person's job title"),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='A LinkedIn profile for verifying the facility claim', verbose_name='verification LinkedIn profile'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='other_facility_type',
            field=models.CharField(blank=True, help_text='Editable alternate text when facility type is OTHER.', max_length=200, null=True, verbose_name='description of other facility type'),
        ),
    ]
