# Generated by Django 2.0.13 on 2019-07-12 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_facilityclaim_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_affiliations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Benefits for Business and Workers (BBW)', 'Benefits for Business and Workers (BBW)'), ('Better Mills Program', 'Better Mills Program'), ('Better Work (ILO)', 'Better Work (ILO)'), ('Canopy', 'Canopy'), ('Ethical Trading Initiative', 'Ethical Trading Initiative'), ('Fair Labor Association', 'Fair Labor Association'), ('Fair Wear Foundation', 'Fair Wear Foundation'), ('SEDEX', 'SEDEX'), ('Social and Labor Convergence Plan (SLCP)', 'Social and Labor Convergence Plan (SLCP)'), ('Sustainable Apparel Coalition', 'Sustainable Apparel Coalition'), ('Sweatfree Purchasing Consortium', 'Sweatfree Purchasing Consortium')], help_text='A group the facility is affiliated with', max_length=50, verbose_name='facility affiliation'), blank=True, help_text="The facility's affiliations", null=True, size=None, verbose_name='facility affilations'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BCI', 'BCI'), ('B Corp', 'B Corp'), ('Bluesign', 'Bluesign'), ('Canopy', 'Canopy'), ('Cradle to Cradle', 'Cradle to Cradle'), ('EU Ecolabel', 'EU Ecolabel'), ('FSC', 'FSC'), ('Global Recycling Standard (GRS)', 'Global Recycling Standard (GRS)'), ('GOTS', 'GOTS'), ('Green Screen for Safer Chemicals', 'Green Screen for Safer Chemicals'), ('Higg Index', 'Higg Index'), ('IMO Control', 'IMO Control'), ('International Wool Textile Organisation (IWTO)', 'International Wool Textile Organisation (IWTO)'), ('ISO 9000', 'ISO 9000'), ('IVN leather', 'IVN leather'), ('Leather Working Group', 'Leather Working Group'), ('Nordic Swan', 'Nordic Swan'), ('Oeko-Tex Standard 100', 'Oeko-Tex Standard 100'), ('Oeko-Tex STeP', 'Oeko-Tex STeP'), ('Oeko-Tex Eco Passport', 'Oeko-Tex Eco Passport'), ('Oeko-Tex Made in Green', 'Oeko-Tex Made in Green'), ('PEFC', 'PEFC'), ('REACH', 'REACH'), ('Responsible Down Standard (RDS)', 'Responsible Down Standard (RDS)'), ('Responsible Wool Standard (RWS)', 'Responsible Wool Standard (RWS)'), ('SA8000', 'SA8000')], help_text='A certification the facility has achieved', max_length=50, verbose_name='facility certification'), blank=True, help_text="The facility's certifications", null=True, size=None, verbose_name='facility certifications'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_affiliations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Benefits for Business and Workers (BBW)', 'Benefits for Business and Workers (BBW)'), ('Better Mills Program', 'Better Mills Program'), ('Better Work (ILO)', 'Better Work (ILO)'), ('Canopy', 'Canopy'), ('Ethical Trading Initiative', 'Ethical Trading Initiative'), ('Fair Labor Association', 'Fair Labor Association'), ('Fair Wear Foundation', 'Fair Wear Foundation'), ('SEDEX', 'SEDEX'), ('Social and Labor Convergence Plan (SLCP)', 'Social and Labor Convergence Plan (SLCP)'), ('Sustainable Apparel Coalition', 'Sustainable Apparel Coalition'), ('Sweatfree Purchasing Consortium', 'Sweatfree Purchasing Consortium')], help_text='A group the facility is affiliated with', max_length=50, verbose_name='facility affiliation'), blank=True, help_text="The facility's affiliations", null=True, size=None, verbose_name='facility affilations'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BCI', 'BCI'), ('B Corp', 'B Corp'), ('Bluesign', 'Bluesign'), ('Canopy', 'Canopy'), ('Cradle to Cradle', 'Cradle to Cradle'), ('EU Ecolabel', 'EU Ecolabel'), ('FSC', 'FSC'), ('Global Recycling Standard (GRS)', 'Global Recycling Standard (GRS)'), ('GOTS', 'GOTS'), ('Green Screen for Safer Chemicals', 'Green Screen for Safer Chemicals'), ('Higg Index', 'Higg Index'), ('IMO Control', 'IMO Control'), ('International Wool Textile Organisation (IWTO)', 'International Wool Textile Organisation (IWTO)'), ('ISO 9000', 'ISO 9000'), ('IVN leather', 'IVN leather'), ('Leather Working Group', 'Leather Working Group'), ('Nordic Swan', 'Nordic Swan'), ('Oeko-Tex Standard 100', 'Oeko-Tex Standard 100'), ('Oeko-Tex STeP', 'Oeko-Tex STeP'), ('Oeko-Tex Eco Passport', 'Oeko-Tex Eco Passport'), ('Oeko-Tex Made in Green', 'Oeko-Tex Made in Green'), ('PEFC', 'PEFC'), ('REACH', 'REACH'), ('Responsible Down Standard (RDS)', 'Responsible Down Standard (RDS)'), ('Responsible Wool Standard (RWS)', 'Responsible Wool Standard (RWS)'), ('SA8000', 'SA8000')], help_text='A certification the facility has achieved', max_length=50, verbose_name='facility certification'), blank=True, help_text="The facility's certifications", null=True, size=None, verbose_name='facility certifications'),
        ),
    ]
