# Generated by Django 2.0.13 on 2019-07-12 18:05

from django.db import migrations, models


def noop(apps, schema_editor):
    pass


def load_production_types(apps, schema_editor):
        ProductionType = apps.get_model('api', 'ProductionType')
        ProductionType.objects.bulk_create([
            ProductionType(value=v) for v in (
                'Cutting',
                'Denim Services',
                'Embroidery',
                'Fabric Dyeing',
                'Fabric Sourcing',
                'Fabric Weaving',
                'Ginning',
                'Hand Sewing',
                'Knitting',
                'Laundry',
                'Marker Making',
                'Packing',
                'Pattern Grading',
                'Pattern Making',
                'Pleating',
                'Printing',
                'Sample Making',
                'Scouring',
                'Sewing',
                'Shoe Stitching',
                'Spinning',
                'Tanning',
                'Trimming/Embellishment',
            )
        ])


def load_product_types(apps, schema_editor):
        ProductType = apps.get_model('api', 'ProductType')
        ProductType.objects.bulk_create([
            ProductType(value=v) for v in (
                'Accessories',
                'Active Wear',
                'Aprons',
                'Athletic Uniforms',
                'Bags & Soft Cases',
                'Bedskirts',
                'Belts',
                'Bike Shorts',
                'Blouses',
                'Body Wear',
                'Bottoms',
                'Boxer Shorts',
                'Bra Tops',
                'Bras',
                'Bridal',
                'Briefs',
                'Bumpers',
                'Buttons',
                'Caps',
                'Chair Covers',
                'Coats/Outerwear',
                'Cocktail Dresses',
                'Comforters',
                'Costume',
                'Couture',
                'Curtains',
                'Dance Exercisewear',
                'Decorative Pillows',
                'Denim Product',
                'Disposable Uniforms',
                'Dress Shirts',
                'Dresses',
                'Evening',
                'Evening Dresses',
                'Flatlock Activewear',
                'Fleece Bottoms',
                'Fleece Tops',
                'Footwear',
                'Formal Wear',
                'Full/Half Zips',
                'Fur',
                'Gloves',
                'Golf',
                'Hand Loomed Knitwear',
                'Handbags',
                'Head Bands',
                'Headwear',
                'Home',
                'Infant/Baby Bedding',
                'Innerwear/Lingerie',
                'Interlinings',
                'Jackets/Blazers',
                'Jogging Suits',
                'Knit Headwear',
                'Knit Shirts/Tops',
                'Knit Tops',
                'Knits',
                'Lace',
                'Leather Goods',
                'Leggings',
                'Legwear',
                'Lining',
                'Loungewear',
                'Neckwear/Ties',
                'Other',
                'Pants',
                'Polar Fleece',
                'Polo Shirts',
                'Rainwear',
                'Robes',
                'Scarves',
                'Sheets',
                'Shorts',
                'Skirts',
                'Sleepwear',
                'Slips',
                'Socks/Hosiery',
                'Sportswear',
                'Suits',
                'Sweaters',
                'Swimwear',
                'T-Shirts',
                'Table Cloths',
                'Tailored',
                'Trims',
                'Unconstructed Jackets',
                'Uniforms',
                'Vests',
                'Workwear',
                'Woven Shirts',
                'Zippers',
            )
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_affiliations_and_certifications_to_facility_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('value', models.CharField(help_text='A suggested value for production type', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(load_production_types, noop),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('value', models.CharField(help_text='A suggested value for product type', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(load_product_types, noop),
    ]
