# Generated by Django 2.0.13 on 2019-07-12 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_productiontype_and_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_product_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A product produced at the facility', max_length=50, verbose_name='product type'), blank=True, help_text='The products produced at the facility', null=True, size=None, verbose_name='product types'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_production_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A production type associated with the facility', max_length=50, verbose_name='production type'), blank=True, help_text='The production types associated with the facility', null=True, size=None, verbose_name='production types'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_product_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A product produced at the facility', max_length=50, verbose_name='product type'), blank=True, help_text='The products produced at the facility', null=True, size=None, verbose_name='product types'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_production_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A production type associated with the facility', max_length=50, verbose_name='production type'), blank=True, help_text='The production types associated with the facility', null=True, size=None, verbose_name='production types'),
        ),
    ]
