# Generated by Django 2.0.13 on 2019-07-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_product_and_production_types_to_facilityclaim'),
        ('api', '0025_require_claim_form_description'),
    ]

    operations = [
    ]
