# Generated by Django 2.2.4 on 2019-08-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_vector_tile_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
    ]
