# Generated by Django 2.2.4 on 2019-08-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_db_index_to_facility_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('name', models.CharField(help_text='The name of a feature with versions.', max_length=100, primary_key=True, serialize=False)),
                ('version', models.IntegerField(help_text='The version number of the feature.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
