# Generated by Django 2.2.3 on 2019-09-10 20:58

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_generate_hexgrid_function_20190909'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='The corrected lat/lng point location of the facility', srid=4326)),
                ('notes', models.TextField(blank=True, help_text='Details regarding the location change process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(help_text='An optional reference to the contributor who submitted the new location', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Contributor')),
                ('created_by', models.ForeignKey(help_text='The superuser that submitted the new location', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(help_text='The Facility on which the location is changing', on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
            ],
        ),
    ]
