# Generated by Django 2.2.3 on 2019-10-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_facility_history_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('LIST', 'LIST'), ('SINGLE', 'SINGLE')], help_text='Did the the facility data arrive in a list or a single item', max_length=6)),
                ('is_active', models.BooleanField(default=True, help_text='True if items from the source should be shown as being associated with the contributor')),
                ('is_public', models.BooleanField(default=True, help_text='True if the public can see factories from this list are associated with the contributor.')),
                ('create', models.BooleanField(default=True, help_text='Should a facility or facility match be created from the facility data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(help_text='The contributor who submitted the facility data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Contributor')),
                ('facility_list', models.OneToOneField(help_text='The related list if the type of the source is LIST.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.FacilityList')),
            ],
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source from which this item was created.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Source'),
        ),
    ]
