# Generated by Django 2.2.3 on 2019-10-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_source_20190926_2048'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facilitylistitem',
            name='api_fli_facility_list_row_idx',
        ),
        migrations.RemoveField(
            model_name='facilitylist',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='facilitylist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='facilitylist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='facilitylistitem',
            name='facility_list',
        ),
        migrations.AlterField(
            model_name='facilitylistitem',
            name='source',
            field=models.ForeignKey(help_text='The source from which this item was created.', on_delete=django.db.models.deletion.PROTECT, to='api.Source'),
        ),
        migrations.AddIndex(
            model_name='facilitylistitem',
            index=models.Index(fields=['source', 'row_index'], name='api_fli_facility_list_row_idx'),
        ),
    ]
