# Generated by Django 2.2.10 on 2020-03-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_can_view_full_contrib_detail_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityclaim',
            name='parent_company',
            field=models.ForeignKey(default=None, help_text='The parent company / supplier group of this facility claim.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_company', to='api.Contributor', verbose_name='parent company / supplier group'),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaim',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='The parent company / supplier group of this facility claim.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor', verbose_name='parent company / supplier group'),
        ),
    ]
