# Generated by Django 2.2.11 on 2020-07-30 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_ppe_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='ppe_contact_phone',
            field=models.CharField(blank=True, help_text='The contact phone number for PPE-related discussion', max_length=100, null=True, verbose_name='ppe contact phone'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ppe_product_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A type of personal protective equipment produced at the facility', max_length=100, verbose_name='ppe product type'), blank=True, help_text='The types of personal protective equipment produced at the facility', null=True, size=None, verbose_name='ppe product types'),
        ),
        migrations.AlterField(
            model_name='facilitylistitem',
            name='ppe_contact_phone',
            field=models.CharField(blank=True, help_text='The contact phone number for PPE-related discussion', max_length=100, null=True, verbose_name='ppe contact phone'),
        ),
        migrations.AlterField(
            model_name='facilitylistitem',
            name='ppe_product_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A type of personal protective equipment produced at the facility', max_length=100, verbose_name='ppe product type'), blank=True, help_text='The types of personal protective equipment produced at the facility', null=True, size=None, verbose_name='ppe product types'),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='ppe_contact_phone',
            field=models.CharField(blank=True, help_text='The contact phone number for PPE-related discussion', max_length=100, null=True, verbose_name='ppe contact phone'),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='ppe_product_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A type of personal protective equipment produced at the facility', max_length=100, verbose_name='ppe product type'), blank=True, help_text='The types of personal protective equipment produced at the facility', null=True, size=None, verbose_name='ppe product types'),
        ),
    ]
