# Generated by Django 2.2.11 on 2020-09-08 18:40

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_expand_ppe_product_types_and_phone'),
    ]

    operations = [
        TrigramExtension()
    ]
