# Generated by Django 2.2.10 on 2020-10-20 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_install_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApiLimit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monthly_limit', models.PositiveIntegerField(help_text='The number of requests a contributor can make monthly.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contributor', models.ForeignKey(blank=True, db_constraint=False, help_text='The contributor to whom the limit applies.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical api limit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalApiBlock',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('until', models.DateTimeField(help_text='The time until which the block is enforced.')),
                ('active', models.BooleanField(default=True, help_text='Whether or not the block should restrict access.')),
                ('limit', models.PositiveIntegerField(help_text='The limit value that was exceeded.')),
                ('actual', models.PositiveIntegerField(help_text='The count that exceeded the limit.')),
                ('grace_limit', models.PositiveIntegerField(blank=True, help_text='An ad-hoc increase in the limit.', null=True)),
                ('grace_reason', models.TextField(blank=True, help_text='For moderators to explain the interactions that led to the grace being granted.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contributor', models.ForeignKey(blank=True, db_constraint=False, help_text='The contributor to whom the block applies.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor')),
                ('grace_created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The person who set the grace_limit.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical api block',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ApiLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.PositiveIntegerField(help_text='The number of requests a contributor can make monthly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.OneToOneField(help_text='The contributor to whom the limit applies.', on_delete=django.db.models.deletion.CASCADE, to='api.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='ApiBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(help_text='The time until which the block is enforced.')),
                ('active', models.BooleanField(default=True, help_text='Whether or not the block should restrict access.')),
                ('limit', models.PositiveIntegerField(help_text='The limit value that was exceeded.')),
                ('actual', models.PositiveIntegerField(help_text='The count that exceeded the limit.')),
                ('grace_limit', models.PositiveIntegerField(blank=True, help_text='An ad-hoc increase in the limit.', null=True)),
                ('grace_reason', models.TextField(blank=True, help_text='For moderators to explain the interactions that led to the grace being granted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(help_text='The contributor to whom the block applies.', on_delete=django.db.models.deletion.CASCADE, to='api.Contributor')),
                ('grace_created_by', models.ForeignKey(help_text='The person who set the grace_limit.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
