# Generated by Django 2.2.10 on 2020-10-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_apiblock_and_apilimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContributorNotifications',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('api_limit_warning_sent_on', models.DateTimeField(help_text='When a limit warning was sent to the contributor.', null=True)),
                ('api_limit_exceeded_sent_on', models.DateTimeField(help_text='When a limit exceeded notice was sent to the contributor.', null=True)),
                ('api_grace_limit_exceeded_sent_on', models.DateTimeField(help_text='When a grace limit exceeded notice was sent to the contributor.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contributor', models.ForeignKey(blank=True, db_constraint=False, help_text='The contributor to whom the notification was sent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contributor notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ContributorNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_limit_warning_sent_on', models.DateTimeField(help_text='When a limit warning was sent to the contributor.', null=True)),
                ('api_limit_exceeded_sent_on', models.DateTimeField(help_text='When a limit exceeded notice was sent to the contributor.', null=True)),
                ('api_grace_limit_exceeded_sent_on', models.DateTimeField(help_text='When a grace limit exceeded notice was sent to the contributor.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.OneToOneField(help_text='The contributor to whom the notification was sent.', on_delete=django.db.models.deletion.CASCADE, to='api.Contributor')),
            ],
        ),
    ]
