# Generated by Django 2.2.11 on 2021-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_yearly_limit_to_apilimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilimit',
            name='monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text='The number of requests a contributor can make monthly.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalapilimit',
            name='monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text='The number of requests a contributor can make monthly.', null=True),
        ),
    ]
