# Generated by Django 2.2.11 on 2021-01-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_make_apilimit_monthly_limit_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilimit',
            name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='historicalapilimit',
            name='monthly_limit',
        ),
        migrations.AlterField(
            model_name='apilimit',
            name='yearly_limit',
            field=models.PositiveIntegerField(help_text='The number of requests a contributor can make per year.'),
        ),
        migrations.AlterField(
            model_name='historicalapilimit',
            name='yearly_limit',
            field=models.PositiveIntegerField(help_text='The number of requests a contributor can make per year.'),
        ),
    ]
