# Generated by Django 2.2.17 on 2021-02-05 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_apilimit_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_closed',
            field=models.BooleanField(help_text='Whether this facility is closed.', null=True),
        ),
        migrations.AddField(
            model_name='historicalfacility',
            name='is_closed',
            field=models.BooleanField(help_text='Whether this facility is closed.', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalFacilityActivityReport',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reason_for_report', models.TextField(blank=True, help_text='The reason for requesting this status change.', null=True, verbose_name='reason for report')),
                ('closure_state', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], help_text='Whether the facility is open or closed.', max_length=6, verbose_name='closure state')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the report was approved, if applicable.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', help_text='The current status of the report.', max_length=200)),
                ('status_change_reason', models.TextField(blank=True, help_text='The reason entered when changing the status of this report.', null=True, verbose_name='status change reason')),
                ('status_change_date', models.DateTimeField(blank=True, null=True, verbose_name='status change date')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facility', models.ForeignKey(blank=True, db_constraint=False, help_text='The facility to which this report applies.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Facility')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by_contributor', models.ForeignKey(blank=True, db_constraint=False, help_text='The contributor who reported the change.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor', verbose_name='reported by contributor')),
                ('reported_by_user', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who reported the change.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reported by user')),
                ('status_change_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who changed the status of this report', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='status changed by')),
            ],
            options={
                'verbose_name': 'historical facility activity report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FacilityActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_report', models.TextField(blank=True, help_text='The reason for requesting this status change.', null=True, verbose_name='reason for report')),
                ('closure_state', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], help_text='Whether the facility is open or closed.', max_length=6, verbose_name='closure state')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the report was approved, if applicable.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', help_text='The current status of the report.', max_length=200)),
                ('status_change_reason', models.TextField(blank=True, help_text='The reason entered when changing the status of this report.', null=True, verbose_name='status change reason')),
                ('status_change_date', models.DateTimeField(blank=True, null=True, verbose_name='status change date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(help_text='The facility to which this report applies.', on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
                ('reported_by_contributor', models.ForeignKey(help_text='The contributor who reported the change.', on_delete=django.db.models.deletion.PROTECT, to='api.Contributor', verbose_name='reported by contributor')),
                ('reported_by_user', models.ForeignKey(help_text='The user who reported the change.', on_delete=django.db.models.deletion.PROTECT, related_name='reporter_of_activity', to=settings.AUTH_USER_MODEL, verbose_name='reported by user')),
                ('status_change_by', models.ForeignKey(blank=True, help_text='The user who changed the status of this report', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changer_of_status', to=settings.AUTH_USER_MODEL, verbose_name='status changed by')),
            ],
        ),
    ]
