# Generated by Django 2.2.19 on 2021-05-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_add_embed_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonstandardField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(help_text='The column name of the field.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(help_text='The contributor who submitted this field', on_delete=django.db.models.deletion.CASCADE, to='api.Contributor')),
            ],
            options={
                'unique_together': {('contributor', 'column_name')},
            },
        ),
    ]
