# Generated by Django 2.2.22 on 2021-05-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_add_nonstandard_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedconfig',
            name='show_other_contributor_information',
        ),
    ]
