# Generated by Django 2.2.22 on 2021-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_embedconfig_show_other_contributor_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='embed_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Embed'), (2, 'Embed+'), (3, 'Embed Deluxe / Custom Embed')], help_text='The embedded map level that is enabled for the contributor', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontributor',
            name='embed_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Embed'), (2, 'Embed+'), (3, 'Embed Deluxe / Custom Embed')], help_text='The embedded map level that is enabled for the contributor', null=True),
        ),
    ]
