# Generated by Django 2.2.23 on 2021-05-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_add_embed_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='embed_config',
            field=models.OneToOneField(blank=True, help_text='The embedded map configuration for the contributor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EmbedConfig'),
        ),
    ]
