# Generated by Django 2.2.23 on 2021-06-10 19:24

from django.db import migrations, models


contributor_types = {
    'Auditor': 'Auditor / Certification Scheme / Service Provider',
    'Brand/Retailer': 'Brand / Retailer',
    'Factory / Facility':
    'Facility / Factory / Manufacturing Group / Supplier / Vendor',
    'Manufacturing Group / Supplier / Vendor':
    'Facility / Factory / Manufacturing Group / Supplier / Vendor',
    'Journalist': 'Academic / Researcher / Journalist / Student',
    'Multi Stakeholder Initiative': 'Multi-Stakeholder Initiative',
    'Researcher / Academic': 'Academic / Researcher / Journalist / Student',
    'Service Provider': 'Auditor / Certification Scheme / Service Provider',
    'Student': 'Academic / Researcher / Journalist / Student',
    'Supplier': 'Facility / Factory / Manufacturing Group / Supplier / Vendor',
}


def update_contributor_types(apps, schema_editor):
    Contributor = apps.get_model('api', 'Contributor')
    for type, new_type in contributor_types.items():
        Contributor.objects.filter(contrib_type=type).update(contrib_type=new_type)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_add_facility_claim_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contrib_type',
            field=models.CharField(choices=[('Academic / Researcher / Journalist / Student', 'Academic / Researcher / Journalist / Student'), ('Auditor / Certification Scheme / Service Provider', 'Auditor / Certification Scheme / Service Provider'), ('Brand / Retailer', 'Brand / Retailer'), ('Civil Society Organisation', 'Civil Society Organisation'), ('Facility / Factory / Manufacturing Group / Supplier / Vendor', 'Facility / Factory / Manufacturing Group / Supplier / Vendor'), ('Multi-Stakeholder Initiative', 'Multi-Stakeholder Initiative'), ('Union', 'Union'), ('Other', 'Other')], help_text='The category to which this contributor belongs.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcontributor',
            name='contrib_type',
            field=models.CharField(choices=[('Academic / Researcher / Journalist / Student', 'Academic / Researcher / Journalist / Student'), ('Auditor / Certification Scheme / Service Provider', 'Auditor / Certification Scheme / Service Provider'), ('Brand / Retailer', 'Brand / Retailer'), ('Civil Society Organisation', 'Civil Society Organisation'), ('Facility / Factory / Manufacturing Group / Supplier / Vendor', 'Facility / Factory / Manufacturing Group / Supplier / Vendor'), ('Multi-Stakeholder Initiative', 'Multi-Stakeholder Initiative'), ('Union', 'Union'), ('Other', 'Other')], help_text='The category to which this contributor belongs.', max_length=200),
        ),
        migrations.RunPython(update_contributor_types)
    ]
