# Generated by Django 2.2.23 on 2021-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_consolidate_contributor_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contrib_type',
            field=models.CharField(choices=[('Academic / Researcher / Journalist / Student', 'Academic / Researcher / Journalist / Student'), ('Auditor / Certification Scheme / Service Provider', 'Auditor / Certification Scheme / Service Provider'), ('Brand / Retailer', 'Brand / Retailer'), ('Civil Society Organization', 'Civil Society Organization'), ('Facility / Factory / Manufacturing Group / Supplier / Vendor', 'Facility / Factory / Manufacturing Group / Supplier / Vendor'), ('Multi-Stakeholder Initiative', 'Multi-Stakeholder Initiative'), ('Union', 'Union'), ('Other', 'Other')], help_text='The category to which this contributor belongs.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcontributor',
            name='contrib_type',
            field=models.CharField(choices=[('Academic / Researcher / Journalist / Student', 'Academic / Researcher / Journalist / Student'), ('Auditor / Certification Scheme / Service Provider', 'Auditor / Certification Scheme / Service Provider'), ('Brand / Retailer', 'Brand / Retailer'), ('Civil Society Organization', 'Civil Society Organization'), ('Facility / Factory / Manufacturing Group / Supplier / Vendor', 'Facility / Factory / Manufacturing Group / Supplier / Vendor'), ('Multi-Stakeholder Initiative', 'Multi-Stakeholder Initiative'), ('Union', 'Union'), ('Other', 'Other')], help_text='The category to which this contributor belongs.', max_length=200),
        ),
    ]
