# Generated by Django 2.2.23 on 2021-07-20 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_add_period_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilimit',
            name='period_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the contract began.'),
        ),
        migrations.AlterField(
            model_name='historicalapilimit',
            name='period_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the contract began.'),
        ),
    ]
