# Generated by Django 2.2.23 on 2021-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_facility_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='new_oar_id',
            field=models.CharField(help_text='The new OAR ID where this facility can be found if it hasbeen moved.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalfacility',
            name='new_oar_id',
            field=models.CharField(help_text='The new OAR ID where this facility can be found if it hasbeen moved.', max_length=32, null=True),
        ),
    ]
