# Generated by Django 2.2.23 on 2021-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20210923_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='new_oar_id',
            field=models.CharField(blank=True, help_text='The new OAR ID where this facility can be found if it has been moved.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='new_oar_id',
            field=models.CharField(blank=True, help_text='The new OAR ID where this facility can be found if it has been moved.', max_length=32, null=True),
        ),
    ]
