# Generated by Django 2.2.23 on 2021-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_allow_blank_new_oar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='has_inexact_coordinates',
            field=models.BooleanField(default=False, help_text='Whether this facility has manually adjusted coordinates known to be inexact.'),
        ),
        migrations.AddField(
            model_name='historicalfacility',
            name='has_inexact_coordinates',
            field=models.BooleanField(default=False, help_text='Whether this facility has manually adjusted coordinates known to be inexact.'),
        ),
    ]
