# Generated by Django 2.2.24 on 2021-11-01 13:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_add_inexact_coordinates_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExtendedField',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, help_text='Whether or not this field has been verified.')),
                ('field_name', models.CharField(choices=[('country', 'country'), ('name', 'name'), ('address', 'address'), ('number_of_workers', 'number_of_workers'), ('native_language_name', 'native_language_name')], help_text='The name of the field, chosen from a strict list.', max_length=200)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(help_text='The value of the field. An  object with different structure for different fields.Numeric fields are stored as {"min": 1, "max": 2}.If there is a single numeric value, set both min and max to it.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contributor', models.ForeignKey(blank=True, db_constraint=False, help_text='The contributor who submitted this field', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Contributor')),
                ('facility', models.ForeignKey(blank=True, db_constraint=False, help_text='The facility to which this field belongs.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Facility')),
                ('facility_claim', models.ForeignKey(blank=True, db_constraint=False, help_text='The claim from which the field was obtained.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.FacilityClaim')),
                ('facility_list_item', models.ForeignKey(blank=True, db_constraint=False, help_text='The list item from which the field was obtained.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.FacilityListItem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical extended field',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExtendedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, help_text='Whether or not this field has been verified.')),
                ('field_name', models.CharField(choices=[('country', 'country'), ('name', 'name'), ('address', 'address'), ('number_of_workers', 'number_of_workers'), ('native_language_name', 'native_language_name')], help_text='The name of the field, chosen from a strict list.', max_length=200)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(help_text='The value of the field. An  object with different structure for different fields.Numeric fields are stored as {"min": 1, "max": 2}.If there is a single numeric value, set both min and max to it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(help_text='The contributor who submitted this field', on_delete=django.db.models.deletion.CASCADE, to='api.Contributor')),
                ('facility', models.ForeignKey(help_text='The facility to which this field belongs.', on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
                ('facility_claim', models.ForeignKey(blank=True, help_text='The claim from which the field was obtained.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.FacilityClaim')),
                ('facility_list_item', models.ForeignKey(blank=True, help_text='The list item from which the field was obtained.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.FacilityListItem')),
            ],
        ),
    ]
