# Generated by Django 2.2.24 on 2021-11-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_add_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedfield',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='The facility to which this field belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Facility'),
        ),
    ]
