# Generated by Django 2.2.24 on 2021-12-27 19:40

from django.db import migrations, models
from api.helpers import clean


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_embedconfig_prefer_contributor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylistitem',
            name='clean_address',
            field=models.CharField(default='', help_text='The cleaned address of the facility.', max_length=2000),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='clean_name',
            field=models.CharField(default='', help_text='The cleaned name of the facility.', max_length=2000),
        ),
        migrations.AddIndex(
            model_name='facilitylistitem',
            index=models.Index(fields=['country_code', 'clean_name', 'clean_address'], name='api_fli_match_fields_idx'),
        )
    ]
