# Generated by Django 2.2.24 on 2022-01-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_expand_extended_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedconfig',
            name='text_search_label',
            field=models.CharField(blank=True, default='Facility name or OAR ID', help_text='The label for the search box.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='embedfield',
            name='searchable',
            field=models.BooleanField(default=False, help_text='Whether or not to include this field in search.'),
        ),
        migrations.AddField(
            model_name='facilityindex',
            name='custom_text',
            field=models.TextField(help_text='A collection of custom values to search for the facility', null=True),
        ),
    ]
