# Generated by Django 2.2.24 on 2022-02-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_add_processing_type_and_facility_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedfield',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='historicalextendedfield',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
