# Generated by Django 2.2.24 on 2022-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_rename_verified_to_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedconfig',
            name='map_style',
            field=models.CharField(default='default', help_text='The map style for the embedded map', max_length=200),
        ),
    ]
