# Generated by Django 2.2.24 on 2022-02-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_embedconfig_map_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityclaim',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('final product assembly', 'Final Product Assembly'), ('office hq', 'Office / HQ'), ('printing product dyeing and laundering', 'Printing, Product Dyeing and Laundering'), ('raw material processing or production', 'Raw Material Processing or Production'), ('textile or material production', 'Textile or Material Production'), ('warehousing distribution', 'Warehousing / Distribution')], help_text='The editable facility type for this claim.', max_length=300, null=True, verbose_name='facility type'),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaim',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('final product assembly', 'Final Product Assembly'), ('office hq', 'Office / HQ'), ('printing product dyeing and laundering', 'Printing, Product Dyeing and Laundering'), ('raw material processing or production', 'Raw Material Processing or Production'), ('textile or material production', 'Textile or Material Production'), ('warehousing distribution', 'Warehousing / Distribution')], help_text='The editable facility type for this claim.', max_length=300, null=True, verbose_name='facility type'),
        ),
    ]
