# Generated by Django 2.2.24 on 2022-02-18 14:05

import django.contrib.postgres.fields
from django.db import migrations, models

from api.models import get_custom_text


def populate_custom_text_array(apps, schema_editor):
    FacilityIndex = apps.get_model('api', 'FacilityIndex')
    facilities = FacilityIndex.objects.exclude(custom_text='') \
                              .filter(custom_text__isnull=False)
    custom_fields = get_custom_text(facilities.values_list('id', flat=True))

    for facility in facilities.iterator():
        facility.custom_text_array = custom_fields.get(facility.id, list())
        facility.save()


def do_nothing_on_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_facilityindex_extendedfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityindex',
            name='custom_text_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(help_text='A collection of custom values to search for the facility'), default=list, size=None),
        ),
        migrations.RunPython(populate_custom_text_array, do_nothing_on_reverse),
    ]
