# Generated by Django 2.2.24 on 2022-02-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_facilityindex_custom_text_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityindex',
            name='custom_text',
        ),
    ]
