# Generated by Django 2.2.24 on 2022-02-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_facilityindex_custom_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityindex',
            old_name='custom_text_array',
            new_name='custom_text',
        ),
    ]
