# Generated by Django 2.2.24 on 2022-02-25 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_rename_custom_text_array_to_custom_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityclaim',
            name='facility_production_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A processing type associated with the facility', max_length=50, verbose_name='processing type'), blank=True, help_text='The processing types associated with the facility', null=True, size=None, verbose_name='processing types'),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaim',
            name='facility_production_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A processing type associated with the facility', max_length=50, verbose_name='processing type'), blank=True, help_text='The processing types associated with the facility', null=True, size=None, verbose_name='processing types'),
        ),
    ]
