# Generated by Django 2.2.24 on 2022-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_migrate_claim_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_model', models.BinaryField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
