# Generated by Django 2.2.24 on 2022-05-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_trainedmodel'),
        ('api', '0090_remove_duplicate_field_name_choices'),
    ]

    operations = [
    ]
