# Generated by Django 2.2.24 on 2022-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_add_sector_to_facility_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has this contributor has been verified by OS Hub staff.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='embedconfig',
            name='text_search_label',
            field=models.CharField(blank=True, default='Facility name or OS Hub ID', help_text='The label for the search box.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.CharField(editable=False, help_text='The OS Hub ID of a facility.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='new_oar_id',
            field=models.CharField(blank=True, help_text='The new OS Hub ID where this facility can be found if it has been moved.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='facilityalias',
            name='oar_id',
            field=models.CharField(editable=False, help_text='The OS Hub ID of a no longer existent Facility which should be redirected to a different Facility.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilityindex',
            name='id',
            field=models.CharField(db_index=True, editable=False, help_text='The OS Hub ID of a facility.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcontributor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has this contributor has been verified by OS Hub staff.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='id',
            field=models.CharField(db_index=True, editable=False, help_text='The OS Hub ID of a facility.', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='new_oar_id',
            field=models.CharField(blank=True, help_text='The new OS Hub ID where this facility can be found if it has been moved.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityalias',
            name='oar_id',
            field=models.CharField(db_index=True, editable=False, help_text='The OS Hub ID of a no longer existent Facility which should be redirected to a different Facility.', max_length=32),
        ),
    ]
