# Generated by Django 2.2.24 on 2022-06-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_rename_oar_to_os_hub'),
        ('api', '0093_add_sector_to_facility_claim'),
    ]

    operations = [
    ]
