# Generated by Django 2.2.24 on 2022-07-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_merge_20220629_1928'),
        ('api', '0091_merge_20220526_1740'),
    ]

    operations = [
    ]
