# Generated by Django 3.2.14 on 2022-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_merge_20220629_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalapiblock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical api block', 'verbose_name_plural': 'historical api blocks'},
        ),
        migrations.AlterModelOptions(
            name='historicalapilimit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical api limit', 'verbose_name_plural': 'historical api limits'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontributor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contributor', 'verbose_name_plural': 'historical contributors'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontributornotifications',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contributor notifications', 'verbose_name_plural': 'historical contributor notificationss'},
        ),
        migrations.AlterModelOptions(
            name='historicalextendedfield',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical extended field', 'verbose_name_plural': 'historical extended fields'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacility',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facility', 'verbose_name_plural': 'historical facilities'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacilityactivityreport',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facility activity report', 'verbose_name_plural': 'historical facility activity reports'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacilityalias',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facility alias', 'verbose_name_plural': 'historical facility aliases'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacilityclaim',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facility claim', 'verbose_name_plural': 'historical facility claims'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacilityclaimreviewnote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facility claim review note', 'verbose_name_plural': 'historical facility claim review notes'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacilitymatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facility match', 'verbose_name_plural': 'historical facility matches'},
        ),
        migrations.AlterField(
            model_name='historicalapiblock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalapilimit',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontributor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontributornotifications',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalextendedfield',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityactivityreport',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityalias',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaim',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaimreviewnote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilitymatch',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
