# Generated by Django 3.2.4 on 2022-07-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0097_add_facilityclaim_parent_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='The ID of the object for which the event occurred. Set automatically by passing the object to the content_object field.', max_length=32)),
                ('event_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('MERGE', 'MERGE'), ('SPLIT', 'SPLIT'), ('MOVE', 'MOVE'), ('OTHER', 'OTHER'), ('ASSOCIATE', 'ASSOCIATE'), ('DISSOCIATE', 'DISSOCIATE'), ('CLAIM', 'CLAIM'), ('CLAIM_UPDATE', 'CLAIM_UPDATE'), ('CLAIM_REVOKE', 'CLAIM_REVOKE')], help_text='The type of the event, e.g. CLAIM or DELETE.', max_length=50)),
                ('event_time', models.DateTimeField(help_text='The time when the event occurred.')),
                ('event_details', models.JSONField(help_text='Additional information about the event.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The type of the object for which the event occurred. Set automatically by passing the object to the content_object field.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'index_together': {('content_type', 'object_id')},
            },
        ),
    ]
