# Generated by Django 3.2.4 on 2022-07-29 22:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_add_contributor_webhooks_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityclaim',
            name='facility_location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='The lat/lng point location of the facility', null=True, srid=4326, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='facility_location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='The lat/lng point location of the facility', null=True, srid=4326, verbose_name='location'),
        ),
    ]
