# Generated by Django 3.2.4 on 2022-08-05 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_facilitylistitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylist',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='APPROVED', help_text='The current workflow progress of the list.', max_length=200),
        ),
        migrations.AddField(
            model_name='facilitylist',
            name='status_change_by',
            field=models.ForeignKey(help_text='The user who changed the status of this facility list', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver_of_list', to=settings.AUTH_USER_MODEL, verbose_name='status changed by'),
        ),
        migrations.AddField(
            model_name='facilitylist',
            name='status_change_reason',
            field=models.TextField(blank=True, default='', help_text='The reason entered when changing the status of this list.', verbose_name='status change reason'),
        ),
    ]
