# Generated by Django 3.2.4 on 2022-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_add_facilitylist_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylist',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', help_text='The current workflow progress of the list.', max_length=200),
        ),
    ]
