# Generated by Django 3.2.4 on 2022-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_alter_facilitylist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='match_responsibility',
            field=models.CharField(choices=[('moderator', 'OS Hub admins'), ('contributor', 'The contributor')], default='moderator', help_text="Who is responsible for moderating this contributor's data", max_length=12),
        ),
        migrations.AddField(
            model_name='facilitylist',
            name='match_responsibility',
            field=models.CharField(choices=[('moderator', 'OS Hub admins'), ('contributor', 'The contributor')], default='contributor', help_text="Who is responsible for moderating this list's data", max_length=12),
        ),
        migrations.AddField(
            model_name='historicalcontributor',
            name='match_responsibility',
            field=models.CharField(choices=[('moderator', 'OS Hub admins'), ('contributor', 'The contributor')], default='moderator', help_text="Who is responsible for moderating this contributor's data", max_length=12),
        ),
        migrations.AlterField(
            model_name='facilitylist',
            name='match_responsibility',
            field=models.CharField(choices=[('moderator', 'OS Hub admins'), ('contributor', 'The contributor')], default='moderator', help_text="Who is responsible for moderating this list's data", max_length=12),
        ),
    ]
