# Generated by Django 3.2.4 on 2022-09-07 19:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_add_match_responsibility_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='burst_rate',
            field=models.CharField(default=api.models.get_default_burst_rate, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sustained_rate',
            field=models.CharField(default=api.models.get_default_sustained_rate, max_length=20),
        ),
    ]
