# Generated by Django 3.2.4 on 2022-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_add_throttle_rates_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.CharField(max_length=200,
                 primary_key=True, serialize=False)),
            ],
        ),
    ]
