# Generated by Django 3.2.4 on 2022-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_add_throttle_rates_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylist',
            name='file',
            field=models.FileField(blank=True, help_text='The uploaded file.', null=True, upload_to=''),
        ),
    ]
