# Generated by Django 3.2.4 on 2022-09-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_add_facilitylist_to_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='new_oar_id',
            new_name='new_os_id',
        ),
        migrations.RenameField(
            model_name='facilityalias',
            old_name='oar_id',
            new_name='os_id',
        ),
        migrations.RenameField(
            model_name='historicalfacility',
            old_name='new_oar_id',
            new_name='new_os_id',
        ),
        migrations.RenameField(
            model_name='historicalfacilityalias',
            old_name='oar_id',
            new_name='os_id',
        ),
        migrations.AlterField(
            model_name='embedconfig',
            name='text_search_label',
            field=models.CharField(blank=True, default='Facility name or OS ID', help_text='The label for the search box.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.CharField(editable=False, help_text='The OS ID of a facility.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='new_os_id',
            field=models.CharField(blank=True, help_text='The new OS ID where this facility can be found if it has been moved.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='facilityalias',
            name='facility',
            field=models.ForeignKey(help_text='The facility now associated with the os_id', on_delete=django.db.models.deletion.PROTECT, to='api.facility'),
        ),
        migrations.AlterField(
            model_name='facilityalias',
            name='os_id',
            field=models.CharField(editable=False, help_text='The OS ID of a no longer existent Facility which should be redirected to a different Facility.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilityindex',
            name='id',
            field=models.CharField(db_index=True, editable=False, help_text='The OS ID of a facility.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='id',
            field=models.CharField(db_index=True, editable=False, help_text='The OS ID of a facility.', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='new_os_id',
            field=models.CharField(blank=True, help_text='The new OS ID where this facility can be found if it has been moved.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfacilityalias',
            name='facility',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The facility now associated with the os_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.facility'),
        ),
        migrations.AlterField(
            model_name='historicalfacilityalias',
            name='os_id',
            field=models.CharField(db_index=True, editable=False, help_text='The OS ID of a no longer existent Facility which should be redirected to a different Facility.', max_length=32),
        ),
    ]
