# Generated by Django 3.2.4 on 2022-09-19 16:14
from django.db import migrations
from api.constants import Sector


def initialize_sectors(app, schema):
    Sector = app.get_model('api', 'Sector')

    for name in get_initial_sector_names():
        sector = Sector.objects.create(name=name)
        sector.save()


def rollback_initialize_sectors(app, schema):
    Sector = app.get_model('api', 'Sector')
    Sector.objects.filter(name__in=get_initial_sector_names()).delete()


def get_initial_sector_names():
    with open('/usr/local/src/api/data/sectors.csv', 'r') as sector_data:
        sector_data.readline()  # skip header

        names = [Sector.DEFAULT_SECTOR_NAME]
        for line in sector_data:
            name = line.strip('" \n')

            if not name:
                continue

            names.append(name)

        return names


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_sector'),
    ]

    operations = [
        migrations.RunPython(initialize_sectors, rollback_initialize_sectors)
    ]
