# Generated by Django 3.2.4 on 2022-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_trainedmodel_activated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedupeIndexedRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_key', models.TextField()),
                ('record_id', models.CharField(max_length=32)),
                ('record_data', models.TextField()),
            ],
            options={
                'db_table': 'dedupe_indexed_records',
            },
        ),
        migrations.AddIndex(
            model_name='dedupeindexedrecords',
            index=models.Index(fields=['block_key', 'record_id'], name='dedupe_indexed_records_idx'),
        ),
        migrations.AddConstraint(
            model_name='dedupeindexedrecords',
            constraint=models.UniqueConstraint(fields=('block_key', 'record_id'), name='unique_blockkey_recordid'),
        ),
    ]
