# Generated by Django 3.2.4 on 2022-08-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_trainedmodel_activated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='dedupe_indexed_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_key', models.TextField(unique=True)),
                ('record_id', models.CharField(max_length=32, unique=True)),
                ('record_data', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='dedupe_indexed_records',
            index=models.Index(fields=['block_key', 'record_id'], name='dedupe_indexed_records_idx'),
        ),
    ]
