# Generated by Django 3.2.4 on 2022-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_oar_id_to_os_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
