# Generated by Django 3.2.4 on 2022-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_create_add_allow_large_downloads_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedconfig',
            name='hide_sector_data',
            field=models.BooleanField(blank=True, help_text='Whether to hide sector data in the embedded map.', null=True),
        ),
    ]
