# Generated by Django 3.2.4 on 2023-02-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_alter_facilitylistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylist',
            name='replaces',
            field=models.OneToOneField(blank=True, help_text='If not null this list is an updated version of the list specified by this field.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='api.facilitylist'),
        ),
    ]
