# Generated by Django 3.2.4 on 2022-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_trainedmodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainedmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_is_active'),
        ),
    ]
