# Generated by Django 3.2.4 on 2022-10-12 18:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_dedupeindexedrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylist',
            name='file',
            field=models.FileField(blank=True, help_text='The uploaded file.', null=True, upload_to=api.models.list_file_path),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='dedupe_model',
            field=models.FileField(blank=True, null=True, upload_to=api.models.dedupe_model_path),
        ),
    ]
