#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

# fail without OAR_SETTINGS_BUCKET
set -u

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Pull .env files from S3.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pushd "${DIR}"

        echo "Pulling .env.backend from s3://${OAR_SETTINGS_BUCKET}"
        aws s3 cp "s3://${OAR_SETTINGS_BUCKET}/.env.backend" ".env.backend"

        echo "Pulling .env.frontend from s3://${OAR_SETTINGS_BUCKET}"
        aws s3 cp "s3://${OAR_SETTINGS_BUCKET}/.env.frontend" ".env.frontend"

        popd
    fi
fi
