#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Update environment variables file.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pushd "${DIR}"

        if aws s3 cp "s3://${OAR_SETTINGS_BUCKET}/.env" ".env"; then
            echo "Updated environment variables file from ${OAR_SETTINGS_BUCKET}"
        elif [[ ! -f ".env" ]]; then
            cp .env.sample .env
            echo "Updated environment variables file from .env.sample"
        fi

        popd
    fi
fi
