#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
	"Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    # TODO A run of cipublish on Jenkins resulted in an image being published
    # with an 8-character tag. Is this workaround the best solution? This SO
    # answer indicates that --short does not guarantee a length of 7
    # https://stackoverflow.com/a/44287003
    SHORT_SHA="$(git rev-parse --short HEAD)"
    GIT_COMMIT="${SHORT_SHA:0:7}"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Install frontend NPM modules
        docker-compose \
            run --rm --no-deps app \
            yarn install

        # Build static asset bundle for React frontend
        REACT_APP_GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            run --rm --no-deps app \
            yarn run build

        # Build tagged container images
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            build django

        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.batch.yml \
            build batch

        # Make sure the database is up for Django tests
        docker-compose up -d database

        # Test using tagged container images
        GIT_COMMIT="${GIT_COMMIT}" \
            ./scripts/test --ci
    fi
fi
