#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

# fail without OAR_SETTINGS_BUCKET
set -u

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Import database dumps from Sourcemap, run create_master_account_api_key.js, and export new database dumps.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pushd "${DIR}"

        # Download Sourcemap database dumps
        aws s3 cp "s3://${OAR_SETTINGS_BUCKET}/oar_mongodump.tar.gz" ./oar_mongodump.tar.gz

        tar -zxvf ./oar_mongodump.tar.gz

        # Bring up MongoDB and ElasticSearch and respect healthchecks using the Restify service
        docker-compose \
            -f docker-compose.restify.yml \
            up -d restify
        docker-compose \
            -f docker-compose.restify.yml \
            stop restify

        # Run mongorestore on Sourcemap database dumps
        docker-compose \
            -f docker-compose.restify.yml \
            run --rm \
            --entrypoint mongorestore \
            -v "$(pwd)/oar_mongodump/:/opt/oar_mongodump/openapparelregistry" \
            mongo \
            --drop --uri=mongodb://mongo:27017/openapparelregistry /opt/oar_mongodump/ -vvvvv

        # Create and print the master account API key
        docker-compose \
            -f docker-compose.restify.yml \
            run --rm \
            --entrypoint node \
            -v "$(pwd)/src/restify/scripts:/usr/local/src/scripts" \
            restify \
            scripts/create_master_account_api_key.js

        # Run mongodump
        mkdir oar_mongodump_fixed

        docker-compose \
            -f docker-compose.restify.yml \
            run --rm \
        	--entrypoint mongodump \
        	-v "$(pwd)/oar_mongodump_fixed:/opt/oar_mongodump_fixed/" \
        	mongo \
        	--uri=mongodb://mongo:27017/openapparelregistry --out=/opt/oar_mongodump_fixed/

        tar -zcvf oar_mongodump_fixed.tar.gz oar_mongodump_fixed

        docker-compose \
            -f docker-compose.restify.yml \
            down

        rm -rf ./oar_mongodump
        rm ./oar_mongodump.tar.gz

        rm -rf ./oar_mongodump_fixed

        popd
    fi
fi
