#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0") COMMAND OPTION[S]
Execute Terraform subcommands with remote state management.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        TERRAFORM_DIR="$(dirname "$0")/../deployment/terraform"
        echo
        echo "Attempting to deploy application version [${GIT_COMMIT}]..."
        echo "-----------------------------------------------------"
        echo
    fi

    if [[ -n "${OAR_SETTINGS_BUCKET}" ]]; then
        pushd "${TERRAFORM_DIR}"

        aws s3 cp "s3://${OAR_SETTINGS_BUCKET}/terraform/terraform.tfvars" "${OAR_SETTINGS_BUCKET}.tfvars"

        case "${1}" in
            plan)
                DEFAULT_BATCH_CE_DESIRED_CPU=$(aws batch describe-compute-environments --output text --compute-environments "batch${OAR_DEPLOYMENT_ENVIRONMENT^}DefaultComputeEnvironment" --query "computeEnvironments[].computeResources.desiredvCpus")

                # Build Lambda function archives
                make -sC lambda-functions/alert_batch_failures

                # Clear stale modules & remote state, then re-initialize
                rm -rf .terraform terraform.tfstate* 
                terraform init \
                  -backend-config="bucket=${OAR_SETTINGS_BUCKET}" \
                  -backend-config="key=terraform/state"

                terraform plan \
                          -var="image_tag=\"${GIT_COMMIT}\"" \
                          -var="batch_default_ce_desired_vcpus=${DEFAULT_BATCH_CE_DESIRED_CPU:-0}" \
                          -var-file="${OAR_SETTINGS_BUCKET}.tfvars" \
                          -out="${OAR_SETTINGS_BUCKET}.tfplan"
                ;;
            apply)
                terraform apply "${OAR_SETTINGS_BUCKET}.tfplan"

                # Notify Rollbar of the deploy when running on Jenkins
                if [[ -n "${OAR_ROLLBAR_ACCESS_TOKEN}" && -n "${OAR_DEPLOYMENT_ENVIRONMENT}" ]]; then
                    curl -s https://api.rollbar.com/api/1/deploy/ \
                        -F "access_token=${OAR_ROLLBAR_ACCESS_TOKEN}" \
                        -F "environment=${OAR_DEPLOYMENT_ENVIRONMENT}" \
                        -F "revision=${GIT_COMMIT}" \
                        -F "local_username=jenkins"
                fi
                ;;
            *)
                echo "ERROR: I don't have support for that Terraform subcommand!"
                exit 1
                ;;
        esac

        popd
    else
        echo "ERROR: No OAR_SETTINGS_BUCKET variable defined."
        exit 1
    fi
fi
