#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Run linters on the project's code.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint Bash scripts
        if command -v shellcheck > /dev/null; then
            shellcheck scripts/*
        fi

        # Lint React frontend
        docker-compose \
            run --rm --no-deps app \
            yarn lint

        # Lint Django app
        docker-compose \
            run --rm --no-deps --entrypoint flake8 django \
            --exclude settings.py,manage.py,*.pyc,api/migrations/*
    fi
fi
