#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Reset database and repopulate with fixture data including facilities & matches.
"
}

function resetdb() {
    ./scripts/manage resetdb
}

function processfixtures() {
    ./scripts/manage processfixtures
}

function enableswitches() {
    ./scripts/manage waffle_switch vector_tile on
    ./scripts/manage waffle_switch claim_a_facility on
    ./scripts/manage waffle_switch ppe on
    ./scripts/manage waffle_switch report_a_facility on
}

function assigngroups() {
    ./scripts/manage user_groups -e c2@example.com -a add -g can_submit_facility
    ./scripts/manage user_groups -e c2@example.com -a add -g can_submit_private_facility
    ./scripts/manage user_groups -e c2@example.com -a add -g can_get_facility_history
    ./scripts/manage user_groups -e c2@example.com -a add -g can_view_full_contrib_detail
}

function maketoken() {
    ./scripts/manage shell -c "from rest_framework.authtoken.models import Token; from api.models import User; token = Token.objects.create(user=User.objects.get(id=2),key='1d18b962d6f976b0b7e8fcf9fcc39b56cf278051'); print('Token for c2@example.com'); print(token)"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        resetdb
        enableswitches
        processfixtures
        assigngroups
        maketoken
    fi
fi
