#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Reset database and repopulate with fixture data including facilities & matches.
"
}

function resetdb() {
    ./scripts/manage resetdb
}

function processfixtures() {
    ./scripts/manage processfixtures
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        resetdb
        processfixtures
    fi
fi
