#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
    	"Usage: $(basename "$0")
Starts servers using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    elif [ "${1:-}" = "--restify" ]; then
        docker-compose \
            -f docker-compose.yml \
        	-f docker-compose.restify.yml \
        	up app restify 
    else
        docker-compose up
    fi
fi
