#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ./scripts/lint

        docker-compose \
            run --rm --no-deps app \
            yarn test

        echo "TODO: Run django unit tests"
        # TODO: https://github.com/azavea/open-apparel-registry/issues/66
    fi
fi
