#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Builds and pulls container images using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Ensure container images are current
        docker-compose build

        # Install frontend NPM modules
        docker-compose \
            run --rm --no-deps app \
            yarn install

        # Build static asset bundle for React frontend
        docker-compose \
            run --rm --no-deps app \
            yarn run build

        # Bring up PostgreSQL and Django in a way that respects
        # configured service health checks.
        docker-compose up -d database django

        # Apply any outstanding Django migrations
        docker-compose \
            run --rm --entrypoint python \
            django \
            manage.py migrate --no-input

        # Collect Django static files
        docker-compose \
            run --rm --entrypoint python \
            django \
            manage.py collectstatic --noinput
    fi
fi
