#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    # The mgmt/manage.py script implements a CLI interface, so pass all
    # arguments to that script naively.
    docker-compose -f ./deployment/docker-compose.yml run --rm manage "$@"
fi
